# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: fifthTest

on:
  push:
    branches: [ "main-branch" ]
  pull_request:
    branches: [ "main-branch" ]

jobs:
  hello:

    runs-on: ubuntu-latest

  
    steps:
    - name : hello step
      run: echo "Hello World"
